version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.8
    commands:
      - apt-get update
      - apt-get install zip -y
      - pip3 install --upgrade pip
      - pip3 install --upgrade awscli
  build:
    commands:
      - zip lamdemo-$CODEBUILD_RESOLVED_SOURCE_VERSION.zip lamdemo/** -x "*/__pycache__/*" "*/test.py"
  post-build:
    commands:
      - aws cp lamdemo-$CODEBUILD_RESOLVED_SOURCE_VERSION.zip s3://wol-deployments/
