---
AWSTemplateFormatVersion: '2010-09-09'
Parameters:
  AppName:
    Type: String
  StagingBucket:
    Type: String
  RepoOwner:
    Type: String
  RepoName:
    Type: String
  RepoBranch:
    Type: String
  RepoPAT:
    Type: String
  CodeBuildType:
    Type: String
    Default: LINUX_CONTAINER
  CodeBuildComputeType:
    Type: String
    Default: BUILD_GENERAL1_SMALL
  CodeBuildImage:
    Type: String
    Default: aws/codebuild/standard:4.0
Resources:
  CodeBuildProject:
    Properties:
      Environment:
        ComputeType:
          Ref: CodeBuildComputeType
        Image:
          Ref: CodeBuildImage
        Type:
          Ref: CodeBuildType
      Name:
        Ref: AppName
      ServiceRole: !GetAtt 'CodeBuildRole.Arn'
      Source:
        Type: CODEPIPELINE
        BuildSpec: 'version: 0.2\nphases:\n  install:\n    runtime-versions:\n      python: 3.8\n    commands:\n      - apt-get update\n      - apt-get install zip -y\n      - pip3 install --upgrade pip\n      - pip3 install --upgrade awscli\n  build:\n    commands:\n      - zip lamdemo-$CODEBUILD_RESOLVED_SOURCE_VERSION.zip lamdemo/** -x "*/__pycache__/*" "*/test.py"\n  post-build:\n    commands:\n      - aws cp lamdemo-$CODEBUILD_RESOLVED_SOURCE_VERSION.zip s3://wol-deployments/\n'
      Artifacts:
        Type: CODEPIPELINE
        Location:
          Ref: StagingBucket
    Type: AWS::CodeBuild::Project
  CodeBuildRole:
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Action: sts:AssumeRole
            Effect: Allow
            Principal:
              Service: codebuild.amazonaws.com
        Version: '2012-10-17'
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AdministratorAccess
      Path: /
    Type: AWS::IAM::Role
  CodePipeline:
    Properties:
      ArtifactStore:
        Location:
          Ref: StagingBucket
        Type: S3
      Name:
        Ref: AppName
      RestartExecutionOnUpdate: false
      RoleArn: !GetAtt 'CodePipelineRole.Arn'
      Stages:
        - Actions:
            - ActionTypeId:
                Category: Source
                Owner: ThirdParty
                Provider: GitHub
                Version: '1'
              Configuration:
                Branch:
                  Ref: RepoBranch
                OAuthToken:
                  Ref: RepoPAT
                Owner:
                  Ref: RepoOwner
                PollForSourceChanges: true
                Repo:
                  Ref: RepoName
              Name: SourceStage
              OutputArtifacts:
                - Name: src
              RunOrder: 1
          Name: GetSource
        - Actions:
            - ActionTypeId:
                Category: Build
                Owner: AWS
                Provider: CodeBuild
                Version: '1'
              Configuration:
                ProjectName:
                  Ref: CodeBuildProject
              InputArtifacts:
                - Name: src
              Name: BuildStage
              RunOrder: 1
          Name: Build
    Type: AWS::CodePipeline::Pipeline
  CodePipelineRole:
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Action: sts:AssumeRole
            Effect: Allow
            Principal:
              Service: codepipeline.amazonaws.com
        Version: '2012-10-17'
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonS3FullAccess
        - arn:aws:iam::aws:policy/AWSCodeBuildAdminAccess
        - arn:aws:iam::aws:policy/AWSCodePipelineFullAccess
      Path: /
    Type: AWS::IAM::Role
